- name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
	@@ -35,4 +35,26 @@ jobs:
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --junitxml=pytest.xml --cov-report=xml --cov=src -v | tee pytest-coverage.txt
    - name: Upload pytest test coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage-results
        path: coverage.xml
      if: ${{ always() }}
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: pytest-coverage.txt
        pytest-xml-coverage-path: coverage.xml
        title: Coverage Report
        badge-title: Coverage Badge
        hide-badge: false
        hide-report: false
        create-new-comment: false
        hide-comment: false
        report-only-changed-files: false
        remove-link-from-badge: false
        unique-id-for-comment: python3.8
        junitxml-path: pytest.xml
        junitxml-title: My JUnit Xml Summary Title
